version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./peft-dialogue-summarizer-checkpoint:/app/peft-dialogue-summarizer-checkpoint
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # optional: for CUDA/GPU use

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
